name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DJANGO_SECRET_KEY: "django-insecure-r1d@xi$8hy@z#7*0z55wq9udj(6c%zng56gf7c1r2*06e#!fjx"
  DJANGO_DEBUG: True
  DJANGO_ALLOWED_HOSTS: "*"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11.5]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/base.txt
    - name: Run Tests
      run: |
        python manage.py test
